# Generated by Django 4.2.16 on 2024-11-08 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0002_usermodel_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='username',
        ),
    ]
